#!/bin/sh

#
# brightswing - increase then decrease brightness of light or group rinse and repeat
#             first argument is "light" or "group" the next arg is the ID or name
#
#             set SHOWDELAY to the number of seconds between changes
#
#             to exit early, press <Enter>
#
#

SLDELAY=1			# seconds between changes
MAXBRI=250			# maximum brightness you want
MINBRI=10			# lowest
BRISTEP=5			# increment for increase/decrease
TRANSTIM=1			# set to 1 for quicker transition



# workaround for Ubuntu/Linux dash shell
# doesn't support timed read commands...

if [ "$(uname -o)" = "GNU/Linux" ]; then
	SHL="/usr/bin/bash"
else
	SHL="/bin/sh"
fi

# graceful exit on keypress of Enter

checkexit() {
         if $($SHL -c "read -r -t $SLDELAY"); then
            	printf "\\n"
		huetil restore light $1 $2
		exit
        fi
}

#
# on exits, restore the light
#

trap 'huetil restore $1 $2; exit' INT

# make sure there are arguments

if [ $# -ne 2 ]; then
	echo "brightswing needs 2 arguments"
	echo " i.e. brightswing light 2"
	exit
fi

# check for light or group

case $1 in
	light)
	;;
	group)
	;;
	*)
		echo "need light or group"
		echo "brightswing light|group ID|name"
		exit
	;;
esac

# save initial state

huetil save $1 $2

# set an intial brightness

huetil set $1 $2 bri $MINBRI

# now swing away

brival="$MINBRI"
while true; do
	while [ "$brival" -lt "$MAXBRI" ] && [ "$brival" -lt "255" ]; do
		huetil set $1 $2 bri $brival trans $TRANSTIM
		checkexit $1 $2
		brival="$((brival + BRISTEP))"
	done
	while [ "$brival" -gt "$MINBRI" ] && [ "$brival" -gt "0" ]; do
		huetil set $1 $2 bri $brival trans $TRANSTIM
		checkexit $1 $2
		brival="$((brival - BRISTEP))"
	done
	brival="$MINBRI"             # reset back
done

