#!/bin/sh

#
# xmas - take a group of 2 or 4 lights and have them change
#        between red and green
#

SLDELAY=1		# how lone between changing
TRANSTIM=2		# transition time between color change
numlights=0


savelights() {
	huetil save light $LIGHT1
	huetil save light $LIGHT2
	if [ $numlights = 4 ]; then
		huetil save light $LIGHT3
		huetil save light $LIGHT4
	fi
}

restorelights() {
	huetil restore light $LIGHT1
	huetil restore light $LIGHT2
	if [ $numlights = 4 ]; then
		huetil restore light $LIGHT3
		huetil restore light $LIGHT4
	fi
}

# workaround for Ubuntu/Linux dash shell
# doesn't support timed read commands...

if [ "$(uname -o)" = "GNU/Linux" ]; then
	SHL="/usr/bin/bash"
else
	SHL="/bin/sh"
fi

checkexit() {
         if $($SHL -c "read -r -t $SLDELAY"); then
            	printf "\\n"
		restorelights
		exit
        fi
}

oneway() {
	huetil set light $LIGHT1 color green trans $TRANSTIM
	huetil set light $LIGHT2 color red trans $TRANSTIM
	if [ $numlights = 4 ]; then
		huetil set light $LIGHT3 color green trans $TRANSTIM
		huetil set light $LIGHT4 color red trans $TRANSTIM
	fi
}

otherway() {
	huetil set light $LIGHT1 color red trans $TRANSTIM
	huetil set light $LIGHT2 color green trans $TRANSTIM
	if [ $numlights = 4 ]; then
		huetil set light $LIGHT3 color red trans $TRANSTIM
		huetil set light $LIGHT4 color green trans $TRANSTIM
	fi
}


# main

case $# in
	2)
		LIGHT1="$1"
		LIGHT2="$2"
		numlights=2
	;;
	4)
		LIGHT1="$1"
		LIGHT2="$2"
		LIGHT3="$3"
		LIGHT4="$4"
		numlights=4
	;;
	*)
		echo "xmas: needs 2 or 4 lights..."
		echo " i.e.  xmas 5 6"
		exit
	;;
esac

#
# save present states
#

savelights

#
# on exits, restore the light
#

trap 'restorelights; exit' INT

while true; do
	oneway
	checkexit
	otherway
	checkexit
done
